seed: 0
mixed_precision: false
base_lr: 4.0e-4

nr_gpus: 1
batch_size: 1
n_total_epoch: 600
minibatch_per_epoch: 500

loadmodel: ~
log_dir: "./train_log"
model_save_freq_epoch: 1

max_disp: 256
image_width: 512
image_height: 384
training_data_path: "../CREStereo/stereo_trainset/crestereo"

log_level: "logging.INFO"

gamma: 0.9

